title: Fabio Pizzati
description: Fabio Pizzati
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Fabio Pizzati # add your name
author-img: david-freeman.jpg # add your photo
about-author: PhD student @VisLab and @Inria # add description
author-location: Paris
author-quote: I like cars and AI
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: fabvio # add your Github handle
#social-linkedin: # add your Linkedin handle
social-email: c-fpizzati::at::ambarella__dot__com # add your Email address

navigation:
  - title: About me
    url: /
  - title: Publications
    url: /publications
  - title: Teaching
    url: /teaching
  - title : CV
    url: /cv.pdf
# Disqus
#discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate:
paginate_path: "/page/:num"
sass:
  sass_dir: css/scss

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
